USE NEO_GENESIS
GO
IF EXISTS (SELECT * FROM sys.objects WHERE type = 'P' AND name = 'SP_Delete_JUSTIFICANTE')
BEGIN
    DROP PROCEDURE SP_Delete_JUSTIFICANTE
END
GO

CREATE PROCEDURE SP_Delete_JUSTIFICANTE
    @id INT
AS
BEGIN
    SET NOCOUNT ON;

    DELETE FROM JUSTIFICANTE
    WHERE id_justificante = @id;
END;
GO
