USE NEO_GENESIS
GO

/*
SELECT 
    OBJECT_NAME(fk.parent_object_id) AS SUBCATEGORIA, 
    fk.name AS ForeignKeyName
FROM sys.foreign_keys AS fk
WHERE OBJECT_NAME(fk.parent_object_id) = 'SUBCATEGORIA';


*/


ALTER TABLE SUBCATEGORIA
DROP CONSTRAINT FK__SUBCATEGO__id_us__6225902D;
go

ALTER TABLE SUBCATEGORIA
ADD CONSTRAINT FK_id_usuario_ASPNETUser_SUBCATEGORIA
FOREIGN KEY (id_usuario) 
REFERENCES AspNetUsers(id_usuario);

go

