USE NEO_GENESIS
ALTER TABLE SOLICITUD_MTTO ALTER COLUMN descripcion_problema nvarchar(600) NULL;
ALTER TABLE SOLICITUD_MTTO ALTER COLUMN img_evidencia varchar(200) NULL;
ALTER TABLE SOLICITUD_MTTO ALTER COLUMN img_evidencia2 varchar(200) NULL;
ALTER TABLE SOLICITUD_MTTO ALTER COLUMN img_evidencia3 varchar(200) NULL;
ALTER TABLE SOLICITUD_MTTO ALTER COLUMN img_evidencia4 varchar(200) NULL;
ALTER TABLE SOLICITUD_MTTO ALTER COLUMN estatus nvarchar(30) NULL;
ALTER TABLE SOLICITUD_MTTO ALTER COLUMN costo_reparacion float NULL;
ALTER TABLE SOLICITUD_MTTO ALTER COLUMN tipo_servicio varchar(20) NULL;
ALTER TABLE SOLICITUD_MTTO ALTER COLUMN fecha_servicio char(10) NULL;
ALTER TABLE SOLICITUD_MTTO ALTER COLUMN fecha_entrega char(10) NULL;
ALTER TABLE SOLICITUD_MTTO ALTER COLUMN grado_urgencia nvarchar(40) NULL;

ALTER TABLE SOLICITUD_MTTO
ADD Asignado NVARCHAR(MAX) NULL;

GO
