USE NEO_GENESIS
GO
IF EXISTS (SELECT * FROM sys.objects WHERE type = 'P' AND name = 'SP_Delete_PRESTAMO')
BEGIN
    DROP PROCEDURE SP_Delete_PRESTAMO
END
GO

CREATE PROCEDURE SP_Delete_PRESTAMO
    @id INT
AS
BEGIN
    SET NOCOUNT ON;

    DELETE FROM PRESTAMO
    WHERE id_prestamo = @id;
END;
GO
