USE NEO_GENESIS
GO
IF EXISTS (SELECT * FROM sys.objects WHERE type = 'P' AND name = 'SP_Delete_HORAS_EXTRAS')
BEGIN
    DROP PROCEDURE SP_Delete_HORAS_EXTRAS
END
GO

CREATE PROCEDURE SP_Delete_HORAS_EXTRAS
    @id INT
AS
BEGIN
    SET NOCOUNT ON;

    DELETE FROM HORAS_EXTRAS
    WHERE id_horaExtra = @id;
END;
GO
