USE NEO_GENESIS
GO
IF EXISTS (SELECT * FROM sys.objects WHERE type = 'P' AND name = 'SP_Delete_INCIDENCIA')
BEGIN
    DROP PROCEDURE SP_Delete_INCIDENCIA
END
GO

CREATE PROCEDURE SP_Delete_INCIDENCIA
    @id INT
AS
BEGIN
    SET NOCOUNT ON;

    DELETE FROM INCIDENCIA
    WHERE id_incidencia = @id;
END;
GO

